version: 2
workflows:
  version: 2
  test:
    jobs:
      - java-8
      - java-11
      - java-13
jobs:
  java-8: &test-template
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/masahitojp/botan-core
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    # Dependencies
    #   This would typically go in either a build or a build-and-test job when using workflows
    # Restore the dependency cache
    # This is based on your 1.0 configuration file or project settings
    - run: cp gradle.properties.sample gradle.properties
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
    # This is based on your 1.0 configuration file or project settings
    - run: ./gradlew dependencies
    # Save dependency cache
    - save_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
        paths:
        - ~/masahitojp/botan-core/.gradle
    # Test
    - run: if [ -a ./gradlew ]; then ./gradlew test; else ./gradle test; fi
    # Teardown
    #   If you break your build into multiple jobs with workflows, you will probably want to do the parts of this that are relevant in each
    # Save test results
    - store_test_results:
        path: /tmp/circleci-test-results
    # Save artifacts
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results
  java-11:
    <<: *test-template
    docker:
      - image: circleci/openjdk:11-jdk
  java-13:
    <<: *test-template
    docker:
      - image: circleci/openjdk:13.0.2

